### ISSUE TITLE
Win 10 LOOT 0.10 windows installer wants to reboot PC

### ISSUE THREAD

**Issue by TooManyAccounts** [loot/loot.github.io#59] opened 2016-11-11 08:17 UTC
The windows installer  for LOOT 0.10 tries to reboot your machine after the install completes. If the reboot prompt is dismissed,  LOOT works fine.

Loot Version: Version 0.10.0 (build 7b97241)
Reproducibility:  Always 
OS Name: Microsoft Windows 10 Pro
Windows Version: 10.0.10586 Build 10586

EDIT: added exact LOOT build

**Comment by WrinklyNinja** [comment] 2016-11-11 08:26
Duplicate of loot/loot#692.

**Closed by WrinklyNinja** 2016-11-11 08:26 UTC
